name: Auto Cherry-Pick to Production

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  cherry-pick:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write # needed to create branches
      pull-requests: write # needed to create PRs

    steps:
      - name: Set up Git
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for cherry-pick
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine new branch name & commit
        id: vars
        run: |
          BRANCH=release-${{ github.event.pull_request.number }}
          MERGE_SHA=$(curl -s https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} | jq -r '.merge_commit_sha')
          echo "branch=${BRANCH}" >> $GITHUB_OUTPUT
          echo "sha=${MERGE_SHA}"  >> $GITHUB_OUTPUT

      - name: Create and switch to new branch
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git switch production
          git checkout -b ${{ steps.vars.outputs.branch }}
          git cherry-pick ${{ steps.vars.outputs.sha }}
          git push origin ${{ steps.vars.outputs.branch }} --force

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base production \
            --head ${{ steps.vars.outputs.branch }} \
            --title "Release #${{ github.event.pull_request.number }}" \
            --body "This PR cherry-picks changes from PR #${{ github.event.pull_request.number }} into the production branch." \
            --repo ${{ github.repository }}
